default_platform(:ios)

platform :ios do
  desc "Build and deploy to TestFlight and App Store Connect"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: false
    )

    get_certificates(api_key: api_key)
    get_provisioning_profile(api_key: api_key)

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: "ExportOptions.plist"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
