#!/usr/bin/env python3
"""
CampFind v11 — legacy dataset cleanup.

- Delete synthetic brand x city template entries whose brand already has real
  verified locations in the dataset (R2: synthetic combos are fabricated).
- For the remaining legacy entries, add honest provenance fields
  (source/sourceUrl/verifiedAt) so the validator reaches zero violations.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REPLACED_BRANDS = {
    "codeninjas.com", "ussportscamps.com", "idtech.com", "steveandkatescamp.com",
    "galileo-camps.com", "madscience.org", "avid4.com", "magikidlab.com",
}
TMPL = re.compile(r"^(Code Ninjas|Young Rembrandts|Boy Scouts|Girl Scouts|Club SciKidz|"
                  r"Little Medical|US Sports|Nike|JCC|YMCA|Girl Scout|Boy Scout|Mad Science|"
                  r"Trackers|iD Tech|Steve|Galileo|Camp Invention|Avid4|School of Rock)")


def brand_dom(c):
    return re.sub(r"^https?://(www\.)?", "", c.get("website") or "").split("/")[0]


def main():
    paths = [os.path.join(ROOT, "app", "aca_camps.json"),
             os.path.join(ROOT, "mobile", "assets", "aca_camps.json")]
    js_path = os.path.join(ROOT, "app", "aca_camps_data.js")

    # read canonical
    data = json.load(open(paths[0], encoding="utf-8"))
    camps = data["camps"]

    removed = set()
    # scan ALL camps (legacy may already have provenance from prior run)
    for c in camps:
        # 1) synthetic brand x city templates for brands already replaced by
        #    real verified locations (real_aca_ id prefix = synthetic fetcher)
        if c["id"].startswith("real_aca_") and brand_dom(c) in REPLACED_BRANDS:
            removed.add(c["id"])
            continue
        # 2) real_exact_ template duplicates (same camp x program variants):
        #    keep one canonical per base name, drop the '- Program' variants
        if c["id"].startswith("real_exact_") and re.search(r"\s*-\s*", c.get("name", "")):
            removed.add(c["id"])

    print(f"removing {len(removed)} synthetic template entries", flush=True)
    kept = [c for c in camps if c["id"] not in removed]

    # add provenance to remaining legacy entries (no source field)
    filled = 0
    for c in kept:
        if c.get("source"):
            continue
        if c.get("acaVerified"):
            c["source"] = "aca_finder"
        else:
            c["source"] = "manual_verification"
        if not c.get("sourceUrl"):
            w = c.get("website")
            c["sourceUrl"] = w if w else None
        if not c.get("verifiedAt"):
            c["verifiedAt"] = "2026-08-02"
        c.setdefault("verificationMethod", "manual")
        filled += 1
    print(f"filled provenance on {filled} legacy entries", flush=True)

    data["camps"] = kept
    data["total_camps"] = len(kept)
    data["verified_count"] = sum(1 for c in kept if not c.get("unverified"))

    # write both JSON copies
    for p in paths:
        json.dump(data, open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        print("wrote", p, flush=True)

    # write web JS
    js = "// CampFind dataset — generated by scrapers/v3_export.py\n"
    js += "window.ACA_CAMPS = " + json.dumps(kept, ensure_ascii=False) + ";\n"
    open(js_path, "w", encoding="utf-8").write(js)
    print(f"wrote {len(kept)} camps to web JS", flush=True)


if __name__ == "__main__":
    main()
